[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
brotli = "7.0.0"
flate2 = "1.0.34"
lz4 = "1.28.0"
zstd = "0.13.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "compression_benchmark"
harness = false